export * from './common/types.js';
export * from './browser/index.js';
export * from './api/index.js';

// Tool type constants
export const BROWSER_TOOLS = [
  "playwright_navigate",
  "playwright_screenshot",
  "playwright_click",
  "playwright_iframe_click",
  "playwright_iframe_fill",
  "playwright_fill",
  "playwright_select",
  "playwright_hover",
  "playwright_evaluate",
  "playwright_console_logs",
  "playwright_close",
  "playwright_get_visible_text",
  "playwright_get_visible_html",
  "playwright_click_and_switch_tab",
  "playwright_drag",
  "playwright_press_key",
  "playwright_upload_file",
  "playwright_expect_response",
  "playwright_assert_response",
  "playwright_custom_user_agent",
  "playwright_save_as_pdf",
  "playwright_click_by_test_id",
  "playwright_fill_by_test_id",
  "playwright_click_by_role",
  "playwright_fill_by_role",
  "playwright_click_by_text",
  "playwright_fill_by_text",
  "playwright_click_by_label",
  "playwright_fill_by_label",
  "playwright_click_by_placeholder",
  "playwright_fill_by_placeholder",
  "playwright_click_by_title",
  "playwright_click_by_alt",
  "playwright_double_click",
  "playwright_right_click",
  "playwright_select_option_by_value",
  "playwright_select_option_by_label",
  "playwright_select_multiple_options",
  "playwright_check_element",
  "playwright_uncheck_element",
  "playwright_type_text",
  "playwright_get_element_text",
  "playwright_get_element_attribute",
  "playwright_check_element_exists",
  "playwright_is_element_checked",
  "playwright_get_input_value",
  "playwright_wait_for_element_hidden",
  "playwright_wait_for_url_change",
  "playwright_scroll_to_element",
  "playwright_take_element_screenshot"
];

export const API_TOOLS = [
  "playwright_get",
  "playwright_post",
  "playwright_put",
  "playwright_patch",
  "playwright_delete"
]; 